// consumed in deploy_zklink.js
const DEPLOY_ZKLINK_LOG_PREFIX = 'deploy';
const DEPLOY_LOG_DEPLOYER = "deployer";
const DEPLOY_LOG_GOVERNOR = "governor";
const DEPLOY_LOG_VERIFIER_TARGET = "verifierTarget";
const DEPLOY_LOG_VERIFIER_TARGET_VERIFIED = "verifierTargetVerified";
const DEPLOY_LOG_PERIPHERY_TARGET = "peripheryTarget";
const DEPLOY_LOG_PERIPHERY_TARGET_VERIFIED = "peripheryTargetVerified";
const DEPLOY_LOG_ZKLINK_TARGET = "zkLinkTarget";
const DEPLOY_LOG_ZKLINK_TARGET_VERIFIED = "zkLinkTargetVerified";
const DEPLOY_LOG_DEPLOY_FACTORY = "deployFactory";
const DEPLOY_LOG_DEPLOY_FACTORY_BLOCK_HASH = "deployFactoryBlockHash";
const DEPLOY_LOG_DEPLOY_TX_HASH = "deployTxHash";
const DEPLOY_LOG_DEPLOY_BLOCK_NUMBER = "deployBlockNumber";
const DEPLOY_LOG_ZKLINK_PROXY = "zkLinkProxy";
const DEPLOY_LOG_VERIFIER_PROXY = "verifierProxy";
const DEPLOY_LOG_GATEKEEPER = "gatekeeper";
const DEPLOY_LOG_ZKLINK_PROXY_VERIFIED = "zkLinkProxyVerified";
const DEPLOY_LOG_VERIFIER_PROXY_VERIFIED = "verifierProxyVerified";
const DEPLOY_LOG_GATEKEEPER_VERIFIED = "gatekeeperVerified";

// consumed in deploy_lz_bridge.js
const DEPLOY_LZ_BRIDGE_LOG_PREFIX = 'deploy_lz_bridge';
const DEPLOY_LOG_LZ_BRIDGE = "lzBridge";
const DEPLOY_LOG_LZ_BRIDGE_VERIFIED = "lzBridgeVerified";

module.exports = {
    DEPLOY_ZKLINK_LOG_PREFIX,
    DEPLOY_LOG_DEPLOYER,
    DEPLOY_LOG_GOVERNOR,
    DEPLOY_LOG_VERIFIER_TARGET,
    DEPLOY_LOG_VERIFIER_TARGET_VERIFIED,
    DEPLOY_LOG_PERIPHERY_TARGET,
    DEPLOY_LOG_PERIPHERY_TARGET_VERIFIED,
    DEPLOY_LOG_ZKLINK_TARGET,
    DEPLOY_LOG_ZKLINK_TARGET_VERIFIED,
    DEPLOY_LOG_DEPLOY_FACTORY,
    DEPLOY_LOG_DEPLOY_FACTORY_BLOCK_HASH,
    DEPLOY_LOG_DEPLOY_TX_HASH,
    DEPLOY_LOG_DEPLOY_BLOCK_NUMBER,
    DEPLOY_LOG_ZKLINK_PROXY,
    DEPLOY_LOG_VERIFIER_PROXY,
    DEPLOY_LOG_GATEKEEPER,
    DEPLOY_LOG_ZKLINK_PROXY_VERIFIED,
    DEPLOY_LOG_VERIFIER_PROXY_VERIFIED,
    DEPLOY_LOG_GATEKEEPER_VERIFIED,
    DEPLOY_LZ_BRIDGE_LOG_PREFIX,
    DEPLOY_LOG_LZ_BRIDGE,
    DEPLOY_LOG_LZ_BRIDGE_VERIFIED
};